version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      CKEditor:
        patterns:
          - "@ckeditor/*"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
